### ISSUE TITLE
pica长篇漫画 集数显示不全

### ISSUE THREAD

**Issue by imddao** [axlecho/MHViewer#8]
部分长篇漫画，在详情页面集数会显示不全，希望能改进一下

**Comment by axlecho** [comment]
请提供更详细的信息

**Comment by Agape2077** [comment]
没看到这个问题差点新开一个issue
bika那边可能因为种种原因将长篇漫画集数分割加载。以天降之物为例，在点进去之后只会加载到第38话，而往前的集数会留给用户点击加载更多按钮后出现
![Screenshot_20200224-013210](https://user-images.githubusercontent.com/14299947/75116670-c2710200-56a5-11ea-96d8-711a2f17f94a.png)
![Screenshot_20200224-013201](https://user-images.githubusercontent.com/14299947/75116676-cef55a80-56a5-11ea-8ec6-8e2ee4845c0f.png)
而在mhviewer中，会出现只加载一次而不对后续部分进行检查从而出现显示不全的问题。
![Screenshot_20200224-013001](https://user-images.githubusercontent.com/14299947/75116706-fcda9f00-56a5-11ea-817e-bcb2b1b21afb.png)

**Comment by axlecho** [comment]
ok，我看下

**Comment by axlecho** [comment]
fix on [v0.0.5](https://github.com/axlecho/MHViewer/releases/tag/v0.0.5)
