### ISSUE TITLE
[Bug 反馈]Pic源登录失效

### ISSUE THREAD

**Issue by Merlyx** [axlecho/MHViewer#9]
奇怪的错误

**Comment by axlecho** [comment]
1.请下载最新的客户端
2.pica最新的一版更新了账户系统，需要使用pica官方客户端登录修改，新的账户系统不再使用邮箱登陆

**Comment by Merlyx** [comment]
> 1.请下载最新的客户端
> 2.pica最新的一版更新了账户系统，需要使用pica官方客户端登录修改，新的账户系统不再使用邮箱登陆

好了 我下成beta2的了
